### ISSUE TITLE
Traduction manquante

### ISSUE THREAD

**Issue by Magicalex** [milescellar/flarum-ext-french#6]
ici il manque : username, password, set new password, groups
![](https://images.mondedie.fr/aSUn2ctk/A5I6OOar.png)

et ici c'est dans l'espace admin : add extension
![](https://images.mondedie.fr/QICcAAGa/cCxLBpYE.png)

**Comment by milescellar** [comment]
Oui, malheureusement ce n'est pas dû à la traduction, les variables n'ont juste pas encore intégrées aux fichiers de langue. Merci du feedback en tout cas ! 👍

**Comment by milescellar** [comment]
Bientôt mis en place : https://github.com/flarum/flarum-ext-english/pull/92/files

**Comment by milescellar** [comment]
Pour information, vu que ça n'avait pas l'air d'être constaté par quelqu'un avant, j'ai envoyé moi-même un pull request qui devrait corriger le titre pour ajouter une extension (la partie manquante) : 
- https://github.com/flarum/core/pull/1094
- https://github.com/flarum/flarum-ext-english/pull/93

**Comment by milescellar** [comment]
#9 merged. #8 en attente pour le moment.
