### ISSUE TITLE
Courrier SMTP

### ISSUE THREAD

**Issue by nibreh** [milescellar/flarum-ext-french#7]
Salut ! Merci pour la traduction !

Je me demandais comment traduire les messages envoyés par mail via SMTP ? On y trouve "X replied, X mentioned & X made a post". Peut-être que c'est prévu ? 

Cordialement

**Comment by milescellar** [comment]
Salut, mais de rien, merci de l'apprécier !

Aucune idée, seules sont traduites les variables de langue qui sont prévues pour la traduction, cela doit être donc des morceaux qui sont directement codés dans le cœur. Tu peux joindre quelques captures d'écran histoire que je vois ce que ça donne, n'utilisant pas SMTP ?

**Comment by milescellar** [comment]
Aucune réponse et impossible pour moi de reproduire le problème de mon côté, je ferme. 😉
